In [57]:
import numpy as np
a = np.arange(10)
a
a = np.reshape(a,(2,-1))
print(a)
a = np.mean(a, axis=0)
a

[[0 1 2 3 4]
 [5 6 7 8 9]]


array([ 2.5,  3.5,  4.5,  5.5,  6.5])

In [39]:
np.random.choice(5, (2,2), replace=False, p=[0.1, 0.1, 0.2, 0.6, 0])

array([[2, 3],
       [1, 0]])