In [30]:
### import numpy as np
X = np.array([[3,2],[4,5],[7,8]])
X[0,:]

#np.random.choice(5, 3, replace=False)

array([3, 2])

In [31]:
np.argmax(X[0, :])

0

In [12]:
from random import randrange
randrange(100, 1000, 4)

444

In [21]:
x = np.array([1,2,3]) 
y = np.array([[1,2,3], [4,5,6]])

print(x.shape)
print(y.shape)


(3,)
(2, 3)


In [23]:
z = y.dot(x)
print(z)
print(z.shape)

[14 32]
(2,)


In [4]:
x = {}
ke = str(1e-8) +"_"+ str(1e-3)
x.update({ke : {"training accuracy": 13, "validation_accuracy":35}})
print(x)

{'1e-08_0.001': {'training accuracy': 13, 'validation_accuracy': 35}}


In [22]:
import numpy as np
a = np.array([1,2,3])

print(a, np.exp(a), np.sum(np.exp(a)))
print(np.exp(a)/np.sum(np.exp(a)))
print(-np.log(np.exp(a)/np.sum(np.exp(a))))
print(np.sum(-np.log(np.exp(a)/np.sum(np.exp(a)))))

print(np.sum(-np.log(2.71828183/30.1928748506)))


[1 2 3] [  2.71828183   7.3890561   20.08553692] 30.1928748506
[ 0.09003057  0.24472847  0.66524096]
[ 2.40760596  1.40760596  0.40760596]
4.22281789333
2.40760596388


In [ ]:
b = np.array([[1,2,3],[4,5,6]])
c = a.dot(b.transpose(1,0))
print(a)
print(b.transpose(1,0))
print(c)